typography_spectrum: 0.8405101101379842
color:
  saturation: 0.5651360002811998
  brandStrength: 0.39559829817153513
  lightness: 0.6126723939087242
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  rhythmicContrast: 0.36350324703380466
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9075308486353606
analytics:
  twitter: null
  google: null
  facebook: null
name: RadioAwakening
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4739dd6a-530e-43e9-95f3-0b3addc75049.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Radio Awakening
purpose: []
