name: RadioAwakening
favicon: null
layout_spectrum: 0.8913395893760026
typography_spectrum: 0.6838757044170052
title: Radio Awakening
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.39261991484090686
  lightness: 0.9219774219673127
  saturation: 0.16495358967222273
  rhythmicContrast: 0.25726016028784215
purpose: []
