typography_spectrum: 0.9081632
color:
  saturation: 1
  brandStrength: 0.9962406
  lightness: 1
  brandColors:
    - '#3591FF'
    - '#84BEFF'
    - '#000000'
    - '#002C74'
    - '#FFEFDD'
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: RadioAwakening
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4739dd6a-530e-43e9-95f3-0b3addc75049.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Radio Awakening
purpose: []
